### ISSUE TITLE
nice joke lol

### ISSUE THREAD

**Issue by aimxpert** [XXBOT1/apex_glow_aimbot_kernel_driver_included#2]
you bought the source then you call him a scammer
by magic you now sell coding services ?
you are as much scammer 1 as the other /XD

**Comment by XXBOT1** [comment]
i am

> when i see this "**mouse_event(MOUSEEVENTF_MOVE, aX, aY, 0, 0); // enable aimbot when mouse cursor is hidden**" 👨‍🏭🔫 you probably sell the same shit just "modified" little bit /lol

i am not selling this . i just posted for other who buy from him
